### ISSUE TITLE
php artisan acacia:install    Symfony\Component\Process\Exception\ProcessTimedOutException 

### ISSUE THREAD

**Issue by liteshare92** [savannabits/acacia#37] opened 2022-04-23 18:29 UTC
PS C:\Devel_2022\Gpplus\Dev\savanna> php artisan acacia:install --force
******************************
*     Begin Installation     *
******************************

1. Publishing files
   a. Publishing acacia configs
Publishing complete.
   b. Publishing acacia core module
Copied Directory [\vendor\savannabits\acacia\publishes\acacia] To [\acacia]
Publishing complete.
   c. Publishing laravel permission config and migration
Publishing complete.
   d. Publishing laravel scout config
Publishing complete.
Dump autoload

   Symfony\Component\Process\Exception\ProcessTimedOutException 

  The process "composer dump-autoload" exceeded the timeout of 60 seconds.

  at C:\Devel_2022\Gpplus\Dev\savanna\vendor\symfony\process\Process.php:1152
    1148▕ 
    1149▕         if (null !== $this->timeout && $this->timeout < microtime(true) - $this->starttime) {
    1150▕             $this->stop(0);
    1151▕
  ➜ 1152▕             throw new ProcessTimedOutException($this, ProcessTimedOutException::TYPE_GENERAL);
    1153▕         }
    1154▕
    1155▕         if (null !== $this->idleTimeout && $this->idleTimeout < microtime(true) - $this->lastOutputTime) {
    1156▕             $this->stop(0);

  1   C:\Devel_2022\Gpplus\Dev\savanna\vendor\symfony\process\Process.php:652
      Symfony\Component\Process\Process::checkTimeout()

  2   C:\Devel_2022\Gpplus\Dev\savanna\vendor\savannabits\acacia\src\Helpers\Helpers.php:23
      Symfony\Component\Process\Process::getIterator()
PS C:\Devel_2022\Gpplus\Dev\savanna>

**Comment by coolsam726** [comment] 2022-04-26 03:05
Hi @liteshare92,
I still haven't been able to reproduce this error. Would you please add the reproduction steps? Thanks

**Comment by coolsam726** [comment] 2022-05-10 04:49
@liteshare92 this appears like an issue with your dev environment, although I could be wrong. I will proceed to close this issue. However, if the issue is still persisting, feel free to re-open the issue.

**Closed by coolsam726** 2022-05-10 04:49 UTC

**Comment by coolsam726** [comment] 2022-05-11 07:08
I finally encountered the same issue. The issue occurs when npm takes longer than (30 sec?) to install dependencies during installation. If this happens, just run `npm install` manually first so that the packages can be cached locally, then repeat `php artisan acacia:install`.
